import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header";
import ScrollbarThumb from "./ScrollbarThumb";
import BurgerMenu from "./BurgerMenu";
import ScrollFriction from "./ScrollFriction";

// 💡 [추가] 장바구니 상태와 서랍(Drawer) 컴포넌트 불러오기
import { CartProvider } from "@/contexts/CartContext";
import CartDrawer from "@/components/CartDrawer";

// 💡 [추가] 1440px 고정 레이어들을 반응형으로 만들어 줄 래퍼 불러오기
// (파일 경로가 다르면 알맞게 수정해주세요)
import ResponsiveLayoutWrapper from "./ResponsiveLayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black m-0 p-0">
        <CartProvider>
          <Header />
          <ScrollFriction />

          {/* 층 1️⃣ [가장 아래] head - sunji 레이어 (zIndex: 920) */}
          <ResponsiveLayoutWrapper zIndex={920}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/images/head - sunji.png"
              alt=""
              style={{
                position: "absolute",
                top: "97px",
                left: "1361px",
                width: "38px",
                height: "auto",
                pointerEvents: "auto",
              }}
            />
          </ResponsiveLayoutWrapper>

          {/* 층 2️⃣ [중간] 스크롤바 body (zIndex: 927) */}
          <ScrollbarThumb />

          {/* 층 3️⃣ burdo head 레이어 (zIndex: 9400) */}
          <ResponsiveLayoutWrapper zIndex={9400}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/images/burdo head.png"
              alt=""
              style={{
                position: "absolute",
                top: "28px",
                left: "1331px",
                width: "92px",
                height: "auto",
                pointerEvents: "auto",
              }}
            />
          </ResponsiveLayoutWrapper>

          {/* 층 4️⃣ 버거 메뉴 단독 레이어 (zIndex: 9999) */}
          <ResponsiveLayoutWrapper zIndex={9999}>
            <div
              style={{
                position: "absolute",
                top: "16px",
                left: "1074px",
                pointerEvents: "auto",
              }}
            >
              <BurgerMenu />
            </div>
          </ResponsiveLayoutWrapper>

          {/* 💡 메인 컨텐츠 영역 */}
          <main className="relative w-full flex-grow flex flex-col items-center">
            {children}
          </main>

          {/* 💡 장바구니 서랍 UI */}
          <CartDrawer />
        </CartProvider>
      </body>
    </html>
  );
}